# Generated by Django 6.0.3 on 2026-03-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('cgpa', models.FloatField()),
                ('academic_pressure', models.IntegerField()),
                ('work_pressure', models.IntegerField(default=0)),
                ('study_satisfaction', models.IntegerField()),
                ('job_satisfaction', models.IntegerField(default=0)),
                ('work_study_hours', models.FloatField()),
                ('sleep_duration', models.CharField(choices=[('less than 5 hours', 'Less than 5 hours'), ('5-6 hours', '5-6 hours'), ('7-8 hours', '7-8 hours'), ('more than 8 hours', 'More than 8 hours'), ('others', 'Others')], max_length=50)),
                ('dietary_habits', models.CharField(choices=[('Healthy', 'Healthy'), ('Moderate', 'Moderate'), ('Unhealthy', 'Unhealthy'), ('Others', 'Others')], max_length=50)),
                ('suicidal_thoughts', models.CharField(max_length=10)),
                ('family_history', models.CharField(max_length=10)),
                ('financial_stress', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.survey')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('prediction', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.surveyresponse')),
            ],
        ),
    ]
