# Generated by Django 6.0.3 on 2026-03-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
