# Generated by Django 6.0.3 on 2026-03-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='dietary_habits',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Moderate', 'Moderate'), ('Unhealthy', 'Unhealthy'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='sleep_duration',
            field=models.CharField(choices=[('less than 5 hours', 'Less than 5 hours'), ('5-6 hours', '5-6 hours'), ('7-8 hours', '7-8 hours'), ('more than 8 hours', 'More than 8 hours'), ('others', 'Others')], max_length=50),
        ),
    ]
